CREATE TABLE `AppData` (
  `id` INTEGER PRIMARY KEY,
  `app_id` varchar(100) ,
  `app_name` mediumblob,
  `Developer_id` varchar(100) ,
  `Developer_name` text,
  `Developer_company` mediumblob,
  `average_rating` float,
  `total_raters` int(11) ,
  `Rated_summary` text,
  `1star_num` int(11) ,
  `2star_num` int(11),
  `3star_num` int(11) ,
  `4star_num` int(11) ,
  `5star_num` bigint(11) ,
  `current_version` varchar(50) ,
  `required_android_version` varchar(100),
  `category` varchar(50) ,
  `sub_category` varchar(50) ,
  `price` text,
  `currency` varchar(10) ,
  `thumbnail` varchar(200) ,
  `store_location` varchar(100) ,
  `crawler_point` varchar(100) ,
  `Description` mediumblob,
  `Latest_modified` datetime ,
  `Latest_action` varchar(50),
  `Installs` varchar(50) ,
  `Content_rated` text,
  `Language` text,
  `Requirements` mediumblob,
  `url` mediumblob,
  `size` varchar(20) ,
  `Permission` text,
  `Contact_phone` text,
  `Contact_website` text,
  `Contact_email` text,
  `Promoted_text` text,
  `Promoted_screenshot` text,
  `Promoted_video` text,
  `Recent_changes` mediumblob,
  `latest_reveiw_id` varchar(50) ,
  `rho` float DEFAULT '0',
  `adjusted_rating` float ,
  `average_weekly` float ,
  `weeks` int(11) ,
  `rank` int(11) ,
  `Note` text
);

CREATE TABLE [Comment] (
  [id] INTEGER PRIMARY KEY,
  [appdata_id] [int(11)],
  [reviewer] TEXT,
  [reviewer_id] [varchar(100)],
  [date] datetime,
  [device] [varchar(100)],
  [device_version] mediumblob,
  [rating] [FLOAT(11)],
  [comment] mediumblob,
  [comment_title] mediumblob,
  [helpfulness_ratio] float,
  [helpfulness_agree] [int(11)],
  [helpfulness_total] [int(11)],
  [review_id] [varchar(100)],
  [app_id] [varchar(200)],
  [contribution] float);

CREATE TABLE [Reviewers] (
  [id] INTEGER PRIMARY KEY,
  [reviewer_id] [varchar(50)],
  [app_ids_ordered] text,
  [review_ratings] text,
  [review_dates] text,
  [size] [int(11)],
  [developer_id] text,
  [cluster_id] [int(11)],
  [status] [int(11)],
  [app_versions] TEXT,
  [app_id] [CHAR(50)]);

CREATE TABLE `StoreParameters`(
  `id` INTEGER PRIMARY KEY,
  `code` text,
  `app_store`text,
  `type` text,
  `attr1` text,
  `attr2` text,
  `attr3` text,
  `attr4` text,
  `attr5` text,
  `date` text
);

